# Generated by Django 3.1.2 on 2020-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20201030_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='explanation',
            field=models.CharField(default='Circle Explaination', max_length=100),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(default='circle', max_length=100),
        ),
    ]
