# Generated by Django 3.1.2 on 2020-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20201030_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
