# Generated by Django 3.1.2 on 2020-10-31 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('circle', '0006_auto_20201031_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='DUser',
        ),
    ]
