# Generated by Django 3.1.2 on 2020-10-31 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_auto_20201031_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('memberWrite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='circle',
            name='picture',
            field=models.URLField(default='htttp://none.com', verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='membership',
            name='dateJoined',
            field=models.DateField(default=datetime.date(2020, 10, 31)),
        ),
        migrations.AddField(
            model_name='membership',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(default='None', max_length=500)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.circle')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=100)),
                ('content', models.CharField(default='None', max_length=1000)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.board')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.duser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='None', max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.duser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.post')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.circle'),
        ),
    ]
