# Generated by Django 3.1.2 on 2020-11-06 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0008_auto_20201031_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='memberWrite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='dateJoined',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
    ]
