# Generated by Django 3.1.3 on 2020-11-12 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0009_auto_20201106_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='dateJoined',
            field=models.DateField(default=datetime.date(2020, 11, 12)),
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasRead', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.duser')),
            ],
        ),
    ]
