# Generated by Django 3.1.2 on 2020-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0011_auto_20201113_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
